name: 'Bloat Get Revs'
description: 'Get revisions to compare based on event type'
inputs:
    command:
        description: 'the command keyword to look for in comments'
        default: '/bloat'
    myToken:
        description: 'GitHub API token'
        required: true
outputs:
    base:
        description: 'the base revision'
    fetch:
        description: 'path to fetch to retrieve revisions'
    head:
        description: 'the head revision'
runs:
  using: 'node12'
  main: 'index.js'
