on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to show me errors
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: get old sizes
        id: old
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js
      - name: Checkout
        uses: actions/checkout@v1
      - name: get new sizes
        id: new
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js
      - name: compare
        uses: ./compare # Uses an action in the root directory
        id: bloatcmp
        with:
            old: ${{ steps.old.outputs.rawSizes }}
            new: ${{ steps.new.outputs.rawSizes }}
      # Use the output from the `hello` step
      - name: comment
        uses: ./reply-to-pr-comment
        with:
          stats: ${{ steps.bloatcmp.outputs.stats }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output
        run: echo "output = ${{ steps.bloatcmp.outputs.stats }}"
