on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to show me errors
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Write file one
        run: echo 'hello 123456' > master.txt
        shell: bash
      - name: Write file two
        run: echo 'hello 125456' > new.txt
        shell: bash
      - name: compare sizes
        uses: ./ # Uses an action in the root directory
        id: bloatcmp
        with:
         base_sizes: 'master.txt'
         new_sizes: 'new.txt'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
