on:
  push:
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to show me errors
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: get old sizes
        id: old
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js
      - name: Checkout
        uses: actions/checkout@v1
      - name: get new sizes
        id: new
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js
      - name: Get the output
        env:
          TO_PRINT: ${{ toJson(steps.new.outputs.rawSizes) }}
        run: echo "output = $TO_PRINT"
      - name: Get the output2
        run: echo "output = ${{ toJson(steps.new.outputs.rawSizes) }}"
      - name: compare
        uses: ./compare # Uses an action in the root directory
        id: bloatcmp
        with:
            old: ${{ steps.old.outputs.rawSizes }}
            new: ${{ steps.new.outputs.rawSizes }}
      # Use the output from the `hello` step
      - name: comment
        uses: ./post-comment
        with:
          stats: ${{ steps.bloatcmp.outputs.stats }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
