on:
  #push:
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:

  get_base_rev:
    runs-on: macOS-10.14
    name: build the base rev
    steps:
      - name: print event
        run: echo "${{ github.event_name }} -> ${{ toJSON(github.event) }}"

      - name: get base of pull_request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.base.ref }}

      - name: get base of issue_comment pr
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
        uses: actions/checkout@v1

      - name: build
        run: echo 'do your build in here'

      - name: get sizes
        id: sizes
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js

      - name: debug print sizes
        run: echo "output = ${{ steps.bloatcmp.outputs.stats }}"

  #get_new_rev:
    #runs-on: macOS-10.14
    #name: build the new rev
    #steps:
      #- name: print event
        #run: echo "${{ github.eventName }}: ${{ toJSON(github.event) }}"

      #- name: checkout pr
        #if: github.eventName == 'pull_request'
        #uses: actions/checkout@v1
        #run: touch .bloat-got-rev

      #- name: checkout commented pr
        #if: (github.eventName == 'issue_comment' && github.event.issue.pull_request != null)
        #uses: actions/checkout@v1
        #with:
          #ref: 'pull/${{ github.event.issue.number }}/head'
        #run: touch .bloat-got-rev

      #- name: ensure checkout
        #run: cat .bloat-got-rev

  test_job:
    runs-on: ubuntu-latest
    name: A job to show me errors
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: get old sizes
        id: old
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js
      - name: Checkout
        uses: actions/checkout@v1
      - name: get new sizes
        id: new
        uses: ./get-sizes
        with:
          paths: .github/workflows/hmm.yml get-sizes/index.js compare/index.js
      - name: compare
        uses: ./compare # Uses an action in the root directory
        id: bloatcmp
        with:
            old: ${{ steps.old.outputs.rawSizes }}
            new: ${{ steps.new.outputs.rawSizes }}
      # Use the output from the `hello` step
      - name: comment
        uses: ./post-comment
        with:
          stats: ${{ steps.bloatcmp.outputs.stats }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output
        run: echo "output = ${{ steps.bloatcmp.outputs.stats }}"
