on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to show me errors
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: mkdir
        run: mkdir '.bloatcmp'
      - name: Write file one
        run: echo 'hello 123456' > '.bloatcmp/old.txt'
        shell: bash
      - name: Write file two
        run: echo 'hello 1254568' > '.bloatcmp/new.txt'
        shell: bash
      - run: ls -la
      - name: try getting sizes
        uses: ./get-sizes
        with:
          tag: old
          paths: .bloatcmp/old.txt .bloatcmp/new.txt
        id: getsize
      - name: compare
        uses: ./compare # Uses an action in the root directory
        id: bloatcmp
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "output = ${{ steps.bloatcmp.outputs.bloat_stats }}"
